#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSql.Resource", IsApplication=true)]

namespace AndroidSql
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Calendar.Resource.Attribute.agendaViewHeight = global::AndroidSql.Resource.Attribute.agendaViewHeight;
			global::Com.Syncfusion.Calendar.Resource.Attribute.calendarFirstDayOfWeek = global::AndroidSql.Resource.Attribute.calendarFirstDayOfWeek;
			global::Com.Syncfusion.Calendar.Resource.Attribute.calendarSelectionMode = global::AndroidSql.Resource.Attribute.calendarSelectionMode;
			global::Com.Syncfusion.Calendar.Resource.Attribute.enableDatesInPast = global::AndroidSql.Resource.Attribute.enableDatesInPast;
			global::Com.Syncfusion.Calendar.Resource.Attribute.inlineViewMode = global::AndroidSql.Resource.Attribute.inlineViewMode;
			global::Com.Syncfusion.Calendar.Resource.Attribute.maximumEventIndicatorCount = global::AndroidSql.Resource.Attribute.maximumEventIndicatorCount;
			global::Com.Syncfusion.Calendar.Resource.Attribute.navigateToMonthOnInActiveDatesSelection = global::AndroidSql.Resource.Attribute.navigateToMonthOnInActiveDatesSelection;
			global::Com.Syncfusion.Calendar.Resource.Attribute.navigationArrowThickness = global::AndroidSql.Resource.Attribute.navigationArrowThickness;
			global::Com.Syncfusion.Calendar.Resource.Attribute.navigationButtonHeight = global::AndroidSql.Resource.Attribute.navigationButtonHeight;
			global::Com.Syncfusion.Calendar.Resource.Attribute.navigationButtonWidth = global::AndroidSql.Resource.Attribute.navigationButtonWidth;
			global::Com.Syncfusion.Calendar.Resource.Attribute.navigationEnable = global::AndroidSql.Resource.Attribute.navigationEnable;
			global::Com.Syncfusion.Calendar.Resource.Attribute.showEventsInline = global::AndroidSql.Resource.Attribute.showEventsInline;
			global::Com.Syncfusion.Calendar.Resource.Attribute.showNavigationButtons = global::AndroidSql.Resource.Attribute.showNavigationButtons;
			global::Com.Syncfusion.Calendar.Resource.Attribute.showYearView = global::AndroidSql.Resource.Attribute.showYearView;
			global::Com.Syncfusion.Calendar.Resource.Attribute.toggleDaySelection = global::AndroidSql.Resource.Attribute.toggleDaySelection;
			global::Com.Syncfusion.Calendar.Resource.Attribute.viewMode = global::AndroidSql.Resource.Attribute.viewMode;
			global::Com.Syncfusion.Calendar.Resource.Dimension.activity_horizontal_margin = global::AndroidSql.Resource.Dimension.activity_horizontal_margin;
			global::Com.Syncfusion.Calendar.Resource.Dimension.activity_vertical_margin = global::AndroidSql.Resource.Dimension.activity_vertical_margin;
			global::Com.Syncfusion.Calendar.Resource.Dimension.date_text_size = global::AndroidSql.Resource.Dimension.date_text_size;
			global::Com.Syncfusion.Calendar.Resource.Dimension.date_text_tab_size = global::AndroidSql.Resource.Dimension.date_text_tab_size;
			global::Com.Syncfusion.Calendar.Resource.Dimension.month_row_size = global::AndroidSql.Resource.Dimension.month_row_size;
			global::Com.Syncfusion.Calendar.Resource.Dimension.month_row_tab_size = global::AndroidSql.Resource.Dimension.month_row_tab_size;
			global::Com.Syncfusion.Calendar.Resource.Dimension.month_text_size = global::AndroidSql.Resource.Dimension.month_text_size;
			global::Com.Syncfusion.Calendar.Resource.Dimension.month_text_tab_size = global::AndroidSql.Resource.Dimension.month_text_tab_size;
			global::Com.Syncfusion.Calendar.Resource.Id.agenda = global::AndroidSql.Resource.Id.agenda;
			global::Com.Syncfusion.Calendar.Resource.Id.inline = global::AndroidSql.Resource.Id.inline;
			global::Com.Syncfusion.Calendar.Resource.Id.monthView = global::AndroidSql.Resource.Id.monthView;
			global::Com.Syncfusion.Calendar.Resource.Id.multiRangeSelection = global::AndroidSql.Resource.Id.multiRangeSelection;
			global::Com.Syncfusion.Calendar.Resource.Id.multiSelection = global::AndroidSql.Resource.Id.multiSelection;
			global::Com.Syncfusion.Calendar.Resource.Id.rangeSelection = global::AndroidSql.Resource.Id.rangeSelection;
			global::Com.Syncfusion.Calendar.Resource.Id.singleSelection = global::AndroidSql.Resource.Id.singleSelection;
			global::Com.Syncfusion.Calendar.Resource.Id.yearView = global::AndroidSql.Resource.Id.yearView;
			global::Com.Syncfusion.Calendar.Resource.String.sfcalendar_inlineviewalldaytext = global::AndroidSql.Resource.String.sfcalendar_inlineviewalldaytext;
			global::Com.Syncfusion.Calendar.Resource.String.sfcalendar_inlineviewnoappointmenttext = global::AndroidSql.Resource.String.sfcalendar_inlineviewnoappointmenttext;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar = global::AndroidSql.Resource.Styleable.SfCalendar;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_agendaViewHeight = global::AndroidSql.Resource.Styleable.SfCalendar_agendaViewHeight;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_calendarFirstDayOfWeek = global::AndroidSql.Resource.Styleable.SfCalendar_calendarFirstDayOfWeek;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_calendarSelectionMode = global::AndroidSql.Resource.Styleable.SfCalendar_calendarSelectionMode;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_enableDatesInPast = global::AndroidSql.Resource.Styleable.SfCalendar_enableDatesInPast;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_inlineViewMode = global::AndroidSql.Resource.Styleable.SfCalendar_inlineViewMode;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_maximumEventIndicatorCount = global::AndroidSql.Resource.Styleable.SfCalendar_maximumEventIndicatorCount;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_navigateToMonthOnInActiveDatesSelection = global::AndroidSql.Resource.Styleable.SfCalendar_navigateToMonthOnInActiveDatesSelection;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_navigationArrowThickness = global::AndroidSql.Resource.Styleable.SfCalendar_navigationArrowThickness;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_navigationButtonHeight = global::AndroidSql.Resource.Styleable.SfCalendar_navigationButtonHeight;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_navigationButtonWidth = global::AndroidSql.Resource.Styleable.SfCalendar_navigationButtonWidth;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_navigationEnable = global::AndroidSql.Resource.Styleable.SfCalendar_navigationEnable;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_showEventsInline = global::AndroidSql.Resource.Styleable.SfCalendar_showEventsInline;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_showNavigationButtons = global::AndroidSql.Resource.Styleable.SfCalendar_showNavigationButtons;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_showYearView = global::AndroidSql.Resource.Styleable.SfCalendar_showYearView;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_toggleDaySelection = global::AndroidSql.Resource.Styleable.SfCalendar_toggleDaySelection;
			global::Com.Syncfusion.Calendar.Resource.Styleable.SfCalendar_viewMode = global::AndroidSql.Resource.Styleable.SfCalendar_viewMode;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int agendaViewHeight = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int calendarFirstDayOfWeek = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int calendarSelectionMode = 2130771970;
			
			// aapt resource value: 0x7f01000f
			public const int enableDatesInPast = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int inlineViewMode = 2130771969;
			
			// aapt resource value: 0x7f01000b
			public const int maximumEventIndicatorCount = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int navigateToMonthOnInActiveDatesSelection = 2130771976;
			
			// aapt resource value: 0x7f01000e
			public const int navigationArrowThickness = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int navigationButtonHeight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int navigationButtonWidth = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int navigationEnable = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int showEventsInline = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int showNavigationButtons = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int showYearView = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int toggleDaySelection = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int viewMode = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int date_text_size = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int date_text_tab_size = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int month_row_size = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int month_row_tab_size = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int month_text_size = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int month_text_tab_size = 2130968581;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int agenda = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int inline = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int monthView = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int multiRangeSelection = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int multiSelection = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int rangeSelection = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int singleSelection = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int yearView = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int SampleSQLites = 2130903040;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int sfcalendar_inlineviewalldaytext = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int sfcalendar_inlineviewnoappointmenttext = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SfCalendar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 4
			public const int SfCalendar_agendaViewHeight = 4;
			
			// aapt resource value: 3
			public const int SfCalendar_calendarFirstDayOfWeek = 3;
			
			// aapt resource value: 2
			public const int SfCalendar_calendarSelectionMode = 2;
			
			// aapt resource value: 15
			public const int SfCalendar_enableDatesInPast = 15;
			
			// aapt resource value: 1
			public const int SfCalendar_inlineViewMode = 1;
			
			// aapt resource value: 11
			public const int SfCalendar_maximumEventIndicatorCount = 11;
			
			// aapt resource value: 8
			public const int SfCalendar_navigateToMonthOnInActiveDatesSelection = 8;
			
			// aapt resource value: 14
			public const int SfCalendar_navigationArrowThickness = 14;
			
			// aapt resource value: 12
			public const int SfCalendar_navigationButtonHeight = 12;
			
			// aapt resource value: 13
			public const int SfCalendar_navigationButtonWidth = 13;
			
			// aapt resource value: 6
			public const int SfCalendar_navigationEnable = 6;
			
			// aapt resource value: 5
			public const int SfCalendar_showEventsInline = 5;
			
			// aapt resource value: 7
			public const int SfCalendar_showNavigationButtons = 7;
			
			// aapt resource value: 10
			public const int SfCalendar_showYearView = 10;
			
			// aapt resource value: 9
			public const int SfCalendar_toggleDaySelection = 9;
			
			// aapt resource value: 0
			public const int SfCalendar_viewMode = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
